// Generated by dts-bundle v0.7.3
// Dependencies for this module:
//   ../@fin/disposable
//   ../@fin/event

import { IDisposable } from '@fin/disposable';
import { Event } from '@fin/event';
import { Disposable } from '@fin/disposable';

export interface ICommandEvent {
    commandId: string;
}
export interface ICommandService {
    onWillExecuteCommand: Event<ICommandEvent>;
    executeCommand<T = any>(commandId: string, ...args: any[]): Promise<T>;
}
export interface ICommandsMap {
    [id: string]: ICommand;
}
export interface ICommandHandler {
    (...args: any[]): void;
}
export interface ICommand {
    id: string;
    handler: ICommandHandler;
}
export interface ICommandRegistry {
    registerCommand(id: string, command: ICommandHandler): IDisposable;
    registerCommand(command: ICommand): IDisposable;
    getCommand(id: string): ICommand;
    getCommands(): ICommandsMap;
}
export const CommandsRegistry: ICommandRegistry;

export const NullCommandService: ICommandService;
export class CommandService extends Disposable implements ICommandService {
    readonly onWillExecuteCommand: Event<ICommandEvent>;
    executeCommand<T>(id: string, ...args: any[]): Promise<T>;
    protected _getCommand(id: string): ICommand;
}

